version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - webnet
      - redisnet

  redis:
    image: redis:6-alpine
    networks:
      - redisnet

  daphne:
    volumes:
      - ./cinema/files/static:/static
    env_file:
      - .env
    build:
      context: .
    command: >
      sh -c "python3 manage.py migrate --no-input
             python3 manage.py collectstatic --no-input

             daphne -b 0.0.0.0 -p 8000 cinema.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - webnet
      - redisnet

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - daphne
    networks:
      - webnet

  celery:
    restart: always
    build:
      context: .
    volumes:
      - ./cinema:/cinema
    env_file:
      - .env
    command: sh -c "celery -A cinema worker -l info"
    depends_on:
      - daphne
    networks:
      - webnet
      - redisnet

volumes:
  static:

networks:
  webnet:
  redisnet:
