version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - webnet
      - redisnet

  redis:
    image: redis:6-alpine
    networks:
      - redisnet

  django_asgi:
    volumes:
      - ./cinema:/app
    env_file:
      - .env
    build:
      context: .
    command: >
      sh -c "python3 manage.py migrate --no-input
             python3 manage.py collectstatic --no-input
      
             gunicorn --bind 0.0.0.0:8000 cinema.asgi -w 4 -k uvicorn.workers.UvicornWorker"
#             uvicorn cinema.asgi:application --host 0.0.0.0 --port 8000 --workers 4"
#             python3 manage.py runserver 0.0.0.0:8000"
#             daphne -b 0.0.0.0 -p 8000 cinema.asgi:application"

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - webnet
      - redisnet

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_asgi
    networks:
      - webnet

  celery:
    restart: always
    build:
      context: .
    env_file:
      - .env
    command: sh -c "celery -A cinema worker -l info"
    depends_on:
      - django_asgi
    networks:
      - webnet
      - redisnet

volumes:
  static:
  postgres:

networks:
  webnet:
  redisnet:
