version: '3.8'

services:
  django_gunicorn:
    volumes:
      - ./cinema/files/static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - db
      - django_gunicorn

  redis:
    image: redis:6-alpine
    depends_on:
      - django_gunicorn

  celery:
    restart: always
    build:
      context: .
    volumes:
      - ./cinema:/cinema
    env_file:
      - .env
    depends_on:
      - db
      - nginx
      - django_gunicorn
      - redis

volumes:
  static:
