# Generated by Django 3.2.9 on 2021-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to='main/home/background/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(upload_to='main/home/banners/top', verbose_name='Баннер'),
        ),
    ]
