# Generated by Django 3.2.9 on 2021-11-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211119_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/home/banners/top', verbose_name='Баннер')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='topbanner',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to='main/home/background/', verbose_name='Фоновое изображение'),
        ),
    ]
