# Generated by Django 3.2.9 on 2021-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211121_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsBanner',
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(storage='/mediabanners/background', upload_to='', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(storage='/mediabanners/top', upload_to='', verbose_name='Баннер'),
        ),
    ]
