# Generated by Django 3.2.9 on 2021-11-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211122_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundimage',
            old_name='status',
            new_name='is_active',
        ),
    ]
