# Generated by Django 3.2.9 on 2021-11-22 13:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_backgroundimage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='color',
            field=models.TextField(default='#f4f6f9'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to=main.models.background_path, verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Если не отмечено, вместо картинки фон будет сплошным стандартным цветом'),
        ),
    ]
