# Generated by Django 3.2.9 on 2021-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ua', 'Українська'), ('en', 'English')], default='', max_length=2, verbose_name='Язык'),
        ),
    ]
