# Generated by Django 3.2.9 on 2022-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220315_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian')], max_length=2, verbose_name='Language'),
        ),
    ]
